#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitiesService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sandbox")]
	public partial class UtilitiesServiceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNoWaterUsage(NoWaterUsage instance);
    partial void UpdateNoWaterUsage(NoWaterUsage instance);
    partial void DeleteNoWaterUsage(NoWaterUsage instance);
    #endregion
		
		public UtilitiesServiceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SandboxConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PropNoService> PropNoServices
		{
			get
			{
				return this.GetTable<PropNoService>();
			}
		}
		
		public System.Data.Linq.Table<NoWaterUsage> NoWaterUsages
		{
			get
			{
				return this.GetTable<NoWaterUsage>();
			}
		}
		
		public System.Data.Linq.Table<vwUtilitiesOutagesOverview> vwUtilitiesOutagesOverviews
		{
			get
			{
				return this.GetTable<vwUtilitiesOutagesOverview>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Avista.PropNoService")]
	public partial class PropNoService
	{
		
		private string _ServiceAddress;
		
		private string _ServiceCity;
		
		private string _ServiceState;
		
		private System.Nullable<System.DateTime> _ServiceAsOfDate;
		
		public PropNoService()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceAddress", DbType="VarChar(255)")]
		public string ServiceAddress
		{
			get
			{
				return this._ServiceAddress;
			}
			set
			{
				if ((this._ServiceAddress != value))
				{
					this._ServiceAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCity", DbType="VarChar(100)")]
		public string ServiceCity
		{
			get
			{
				return this._ServiceCity;
			}
			set
			{
				if ((this._ServiceCity != value))
				{
					this._ServiceCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceState", DbType="VarChar(2)")]
		public string ServiceState
		{
			get
			{
				return this._ServiceState;
			}
			set
			{
				if ((this._ServiceState != value))
				{
					this._ServiceState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceAsOfDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ServiceAsOfDate
		{
			get
			{
				return this._ServiceAsOfDate;
			}
			set
			{
				if ((this._ServiceAsOfDate != value))
				{
					this._ServiceAsOfDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="UB.NoWaterUsage")]
	public partial class NoWaterUsage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _SvcLocNbr;
		
		private string _SvcLocBldgNbr;
		
		private string _SvcLocPreDir;
		
		private string _SvcLocStreetName;
		
		private string _SvcLocStreetSuffix;
		
		private string _SvcLocCity;
		
		private System.DateTime _LastNonZeroDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSvcLocNbrChanging(decimal value);
    partial void OnSvcLocNbrChanged();
    partial void OnSvcLocBldgNbrChanging(string value);
    partial void OnSvcLocBldgNbrChanged();
    partial void OnSvcLocPreDirChanging(string value);
    partial void OnSvcLocPreDirChanged();
    partial void OnSvcLocStreetNameChanging(string value);
    partial void OnSvcLocStreetNameChanged();
    partial void OnSvcLocStreetSuffixChanging(string value);
    partial void OnSvcLocStreetSuffixChanged();
    partial void OnSvcLocCityChanging(string value);
    partial void OnSvcLocCityChanged();
    partial void OnLastNonZeroDateChanging(System.DateTime value);
    partial void OnLastNonZeroDateChanged();
    #endregion
		
		public NoWaterUsage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvcLocNbr", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal SvcLocNbr
		{
			get
			{
				return this._SvcLocNbr;
			}
			set
			{
				if ((this._SvcLocNbr != value))
				{
					this.OnSvcLocNbrChanging(value);
					this.SendPropertyChanging();
					this._SvcLocNbr = value;
					this.SendPropertyChanged("SvcLocNbr");
					this.OnSvcLocNbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvcLocBldgNbr", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SvcLocBldgNbr
		{
			get
			{
				return this._SvcLocBldgNbr;
			}
			set
			{
				if ((this._SvcLocBldgNbr != value))
				{
					this.OnSvcLocBldgNbrChanging(value);
					this.SendPropertyChanging();
					this._SvcLocBldgNbr = value;
					this.SendPropertyChanged("SvcLocBldgNbr");
					this.OnSvcLocBldgNbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvcLocPreDir", DbType="VarChar(2)")]
		public string SvcLocPreDir
		{
			get
			{
				return this._SvcLocPreDir;
			}
			set
			{
				if ((this._SvcLocPreDir != value))
				{
					this.OnSvcLocPreDirChanging(value);
					this.SendPropertyChanging();
					this._SvcLocPreDir = value;
					this.SendPropertyChanged("SvcLocPreDir");
					this.OnSvcLocPreDirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvcLocStreetName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SvcLocStreetName
		{
			get
			{
				return this._SvcLocStreetName;
			}
			set
			{
				if ((this._SvcLocStreetName != value))
				{
					this.OnSvcLocStreetNameChanging(value);
					this.SendPropertyChanging();
					this._SvcLocStreetName = value;
					this.SendPropertyChanged("SvcLocStreetName");
					this.OnSvcLocStreetNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvcLocStreetSuffix", DbType="VarChar(5)")]
		public string SvcLocStreetSuffix
		{
			get
			{
				return this._SvcLocStreetSuffix;
			}
			set
			{
				if ((this._SvcLocStreetSuffix != value))
				{
					this.OnSvcLocStreetSuffixChanging(value);
					this.SendPropertyChanging();
					this._SvcLocStreetSuffix = value;
					this.SendPropertyChanged("SvcLocStreetSuffix");
					this.OnSvcLocStreetSuffixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SvcLocCity", DbType="VarChar(20)")]
		public string SvcLocCity
		{
			get
			{
				return this._SvcLocCity;
			}
			set
			{
				if ((this._SvcLocCity != value))
				{
					this.OnSvcLocCityChanging(value);
					this.SendPropertyChanging();
					this._SvcLocCity = value;
					this.SendPropertyChanged("SvcLocCity");
					this.OnSvcLocCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNonZeroDate", DbType="Date NOT NULL")]
		public System.DateTime LastNonZeroDate
		{
			get
			{
				return this._LastNonZeroDate;
			}
			set
			{
				if ((this._LastNonZeroDate != value))
				{
					this.OnLastNonZeroDateChanging(value);
					this.SendPropertyChanging();
					this._LastNonZeroDate = value;
					this.SendPropertyChanged("LastNonZeroDate");
					this.OnLastNonZeroDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwUtilitiesOutagesOverview")]
	public partial class vwUtilitiesOutagesOverview
	{
		
		private System.Nullable<int> _PowerOutages;
		
		private System.Nullable<int> _WaterOutages;
		
		public vwUtilitiesOutagesOverview()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowerOutages", DbType="Int")]
		public System.Nullable<int> PowerOutages
		{
			get
			{
				return this._PowerOutages;
			}
			set
			{
				if ((this._PowerOutages != value))
				{
					this._PowerOutages = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaterOutages", DbType="Int")]
		public System.Nullable<int> WaterOutages
		{
			get
			{
				return this._WaterOutages;
			}
			set
			{
				if ((this._WaterOutages != value))
				{
					this._WaterOutages = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
