<?xml version="1.0" encoding="utf-8"?><Database Name="Sandbox" Class="UtilitiesServiceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cosdwsql;Initial Catalog=Sandbox;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SandboxConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Avista.PropNoService" Member="PropNoServices">
    <Type Name="PropNoService">
      <Column Name="ServiceAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ServiceCity" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ServiceState" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ServiceAsOfDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vwUtilitiesOutagesOverview" Member="vwUtilitiesOutagesOverviews">
    <Type Name="vwUtilitiesOutagesOverview">
      <Column Name="PowerOutages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WaterOutages" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="UB.vwMeterStatus" Member="vwMeterStatus">
    <Type Name="vwMeterStatus">
      <Column Name="[Acct #]" Member="Acct__" Type="System.Decimal" DbType="Decimal(22,0) NOT NULL" CanBeNull="false" />
      <Column Name="[Customer Name]" Member="Customer_Name" Type="System.String" DbType="NVarChar(41)" CanBeNull="true" />
      <Column Name="[Svc Loc Addr]" Member="Svc_Loc_Addr" Type="System.String" DbType="NVarChar(51)" CanBeNull="true" />
      <Column Name="Parcel" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="[Meter Status]" Member="Meter_Status" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="[Meter Status Date]" Member="Meter_Status_Date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="[Status Code]" Member="Status_Code" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>