#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitiesService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sandbox")]
	public partial class UtilitiesServiceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public UtilitiesServiceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SandboxConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UtilitiesServiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PropNoService> PropNoServices
		{
			get
			{
				return this.GetTable<PropNoService>();
			}
		}
		
		public System.Data.Linq.Table<vwUtilitiesOutagesOverview> vwUtilitiesOutagesOverviews
		{
			get
			{
				return this.GetTable<vwUtilitiesOutagesOverview>();
			}
		}
		
		public System.Data.Linq.Table<vwMeterStatus> vwMeterStatus
		{
			get
			{
				return this.GetTable<vwMeterStatus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Avista.PropNoService")]
	public partial class PropNoService
	{
		
		private string _ServiceAddress;
		
		private string _ServiceCity;
		
		private string _ServiceState;
		
		private System.Nullable<System.DateTime> _ServiceAsOfDate;
		
		public PropNoService()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceAddress", DbType="VarChar(255)")]
		public string ServiceAddress
		{
			get
			{
				return this._ServiceAddress;
			}
			set
			{
				if ((this._ServiceAddress != value))
				{
					this._ServiceAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceCity", DbType="VarChar(100)")]
		public string ServiceCity
		{
			get
			{
				return this._ServiceCity;
			}
			set
			{
				if ((this._ServiceCity != value))
				{
					this._ServiceCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceState", DbType="VarChar(2)")]
		public string ServiceState
		{
			get
			{
				return this._ServiceState;
			}
			set
			{
				if ((this._ServiceState != value))
				{
					this._ServiceState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceAsOfDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ServiceAsOfDate
		{
			get
			{
				return this._ServiceAsOfDate;
			}
			set
			{
				if ((this._ServiceAsOfDate != value))
				{
					this._ServiceAsOfDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwUtilitiesOutagesOverview")]
	public partial class vwUtilitiesOutagesOverview
	{
		
		private System.Nullable<int> _PowerOutages;
		
		private System.Nullable<int> _WaterOutages;
		
		public vwUtilitiesOutagesOverview()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PowerOutages", DbType="Int")]
		public System.Nullable<int> PowerOutages
		{
			get
			{
				return this._PowerOutages;
			}
			set
			{
				if ((this._PowerOutages != value))
				{
					this._PowerOutages = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaterOutages", DbType="Int")]
		public System.Nullable<int> WaterOutages
		{
			get
			{
				return this._WaterOutages;
			}
			set
			{
				if ((this._WaterOutages != value))
				{
					this._WaterOutages = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="UB.vwMeterStatus")]
	public partial class vwMeterStatus
	{
		
		private decimal _Acct__;
		
		private string _Customer_Name;
		
		private string _Svc_Loc_Addr;
		
		private string _Parcel;
		
		private string _Meter_Status;
		
		private System.DateTime _Meter_Status_Date;
		
		private string _Status_Code;
		
		public vwMeterStatus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Acct #]", Storage="_Acct__", DbType="Decimal(22,0) NOT NULL")]
		public decimal Acct__
		{
			get
			{
				return this._Acct__;
			}
			set
			{
				if ((this._Acct__ != value))
				{
					this._Acct__ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Customer Name]", Storage="_Customer_Name", DbType="NVarChar(41)")]
		public string Customer_Name
		{
			get
			{
				return this._Customer_Name;
			}
			set
			{
				if ((this._Customer_Name != value))
				{
					this._Customer_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Svc Loc Addr]", Storage="_Svc_Loc_Addr", DbType="NVarChar(51)")]
		public string Svc_Loc_Addr
		{
			get
			{
				return this._Svc_Loc_Addr;
			}
			set
			{
				if ((this._Svc_Loc_Addr != value))
				{
					this._Svc_Loc_Addr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parcel", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Parcel
		{
			get
			{
				return this._Parcel;
			}
			set
			{
				if ((this._Parcel != value))
				{
					this._Parcel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Meter Status]", Storage="_Meter_Status", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string Meter_Status
		{
			get
			{
				return this._Meter_Status;
			}
			set
			{
				if ((this._Meter_Status != value))
				{
					this._Meter_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Meter Status Date]", Storage="_Meter_Status_Date", DbType="DateTime2 NOT NULL")]
		public System.DateTime Meter_Status_Date
		{
			get
			{
				return this._Meter_Status_Date;
			}
			set
			{
				if ((this._Meter_Status_Date != value))
				{
					this._Meter_Status_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Status Code]", Storage="_Status_Code", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Status_Code
		{
			get
			{
				return this._Status_Code;
			}
			set
			{
				if ((this._Status_Code != value))
				{
					this._Status_Code = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
